import React from 'react';
import {
  StyleSheet,
  View,
  Text,
  Image,
  TouchableOpacity,
  ScrollView,
} from "react-native";
import { DrawerActions } from '@react-navigation/native';


const data = [
  {
    id: "1",
    image: require("../assets/email2.png"),
    name: "Better than email",
    date: "With e-invoicing your invoices no longer get lost in someones email inbox.",
  },
  {
    id: "2",
    image: require("../assets/paid.png"),
    name: "Fastest way to get paid",
    date: "E-invoicing is the fastest, most accurate, and cost-effective way to send, process, and validate invoices.",
  },
  {
    id: "3",
    image: require("../assets/clock.png"),
    name: "Invoice status updates",
    date: "Both buyer and seller have real-time visibility into the status of invoices.",
  },
];

const News = [
  {
    id: "1",
    name: "Brand Your Invoice",
  },
  {
    id: "2",
    name: "Add A Professional Header",
  },
  {
    id: "3",
    name: "Include Invoice Information",
  },
  {
    id: "4",
    name: "Include The Dates",
  },
  {
    id: "5",
    name: "Description Of Goods/Services Delivered",
  },
  {
    id: "6",
    name: "Include Tax Details And Highlight The Total Money Owed",
  },
  {
    id: "7",
    name: "Include Payment Terms & Conditions",
  },
];

const Voice = [
  {
    id: "1",
    name: "Streamlined Invoicing Process",
    value:
      "Easy invoice is a completely user friendly GST invoice generator online software.",
  },
  {
    id: "2",
    name: "Professional And Customizable Invoices",
    value:
      "Easy invoice is a completely user friendly GST invoice generator online software.",
  },
  {
    id: "3",
    name: "Automation And Time-Saving",
    value:
      "Easy invoice is a completely user friendly GST invoice generator online software.",
  },
  {
    id: "4",
    name: "Accurate Financial Tracking",
    value:
      "Easy invoice is a completely user friendly GST invoice generator online software.",
  },
  {
    id: "5",
    name: "Payment Integration And Faster Payments",
    value:
      "Easy invoice is a completely user friendly GST invoice generator online software.",
  },
  {
    id: "6",
    name: "Data Security And Backup",
    value:
      "Easy invoice is a completely user friendly GST invoice generator online software.",
  },
  {
    id: "7",
    name: "Multiple Business Invoice Templates",
    value:
      "Easy invoice is a completely user friendly GST invoice generator online software.",
  },
  {
    id: "8",
    name: "Download Invoice In Any Format",
    value:
      "Easy invoice is a completely user friendly GST invoice generator online software.",
  },
  {
    id: "9",
    name: "Direct Mail Facility",
    value:
      "Easy invoice is a completely user friendly GST invoice generator online software.",
  },
];

const task = [
  {
    id: "1",
    name: "Fastest way to get paid?"
  },
  {
    id: "2",
    name: "What is an online invoice generator tool?"
  },
  {
    id: "3",
    name: "How does an online invoice generator tool work?"
  },
  {
    id: "4",
    name: "Are online invoice generator tools secure?"
  },
  {
    id: "5",
    name: "Can I customize the invoices generated by an online invoice generator tool?"
  },
  {
    id: "6",
    name: "Are online invoice generator tools free? "
  },
  {
    id: "7",
    name: "Can I generate an invoice in PDF format?"
  },
  {
    id: "8",
    name: "Is it possible to generate invoices in languages other than English as well?"
  },
  {
    id: "9",
    name: "Is it possible to modify the currency?"
  }
];

const Home=({ navigation }) => {
  
  const onPress = () => {
    navigation.dispatch(DrawerActions.openDrawer());
  };
  return (
    <View style={{ flex: 1 }}>
      <View
        style={{
          height: 106,
          backgroundColor: "#2155CD",
          flexDirection: "row",
          justifyContent: "space-between",
          paddingTop: 40,
        }}
      >
        <View
          style={{
            flexDirection: "row",
            justifyContent: "space-between",
            marginTop: 14,
          }}
        >
          <Text style={styles.text}>EASY INVOICE</Text>
        </View>
        <TouchableOpacity onPress={onPress}>
          <Image
            style={styles.image1}
            source={require("../assets/Square.png")}
          />
        </TouchableOpacity>
      </View>
      <View style={{ flex: 1,backgroundColor:'#FFFFFF' }}>
        <ScrollView>
          {/* <View
            style={{ flexDirection: "row", marginTop: 10, alignSelf: "center" }}
          >
            <Text style={styles.text1}>Online</Text>
            <Text style={styles.text2}>Invoice</Text>
            <Text style={styles.text1}>Generator</Text>
          </View>
          <View style={{ alignSelf: "center", marginTop: 4 }}>
            <Text>Create & download invoices for free</Text>
          </View>
          <TouchableOpacity style={styles.button}>
            <Text style={styles.buttontext}>Create New Invoice</Text>
          </TouchableOpacity> */}

          {/* <View style={{ backgroundColor: "red", marginTop: 4 }}>
            <LottieView
              style={{
                height: 400,
                backgroundColor: "green",
                alignSelf: "center",
              }}
              source={require("../assets/invoice.json")}
              autoPlay
              loop
            />
          </View>

          <View style={{ marginTop: 15 }}>
            <FlatList
              data={data}
              horizontal
              showsHorizontalScrollIndicator={false}
              keyExtractor={(item) => item.id}
              renderItem={({ item }) => (
                <View style={styles.itemContainer}>
                  <Image style={styles.itemImage} source={item.image} />
                  <Text style={styles.itemText}>{item.name}</Text>
                  <Text style={styles.itemText2}>{item.date}</Text>
                </View>
              )}
            />
          </View> */}

          <View>
            <Text
              style={{
                fontSize: 24,
                fontWeight: "bold",
                marginTop: 32,
                textAlign: 'left',
                marginLeft: 16
              }}
            >
              Start With Free Online 
              {"             "}
            
              <Text style={{ fontSize: 24, fontWeight: "bold", color: "blue" }}>
              Invoice Generator
              </Text>
              
            </Text>
          </View>

          <Text
            style={[styles.itemText2, { marginHorizontal: 10 }]}
          >
            Easy Invoice is a professional online invoice generator tool and it
            helps your work and business with a fast and effective way to create
            professional invoices in a few minutes and also it saves time and
            money. Have a perfect solution for small business owners who are
            required to generate online gst invoices in a fast and efficient
            manner so in this case online invoice generator tool will help you.
            {"\n"}
            {"\n"}
            With our best invoice interface, big and small business owners can
            create a gst bill and no need to worry about complex calculations,
            boring and lasting paper work. Our Easy invoice generator software
            has completely customised options, in which users can generate
            invoices as per their requirement. So it helps to grow your
            business.
          </Text>

          <View>
            <Text
              style={{
                fontSize: 24,
                // textAlign: "center",
                fontWeight: "bold",
                marginTop: 32,
                marginLeft: 16
              }}
            >
              Why <Text style={{ fontSize: 24, fontWeight: "bold", color: "blue" }}>E-invoicing?
            </Text>
            </Text>
          </View>
          <View>
            {data.map((item) => {
              return (
                 <View key={item.id} style={styles.itemContainer}>
                  <Image style={styles.itemImage} source={item.image} />
                  <Text style={styles.itemText}>{item.name}</Text>
                  <Text style={styles.itemText2}>{item.date}</Text>
                </View>
                 );
                })}
               </View>


               <View>
            <Text
              style={{
                fontSize: 24,
                // textAlign: "center",
                fontWeight: "bold",
                marginTop: 32,
                marginLeft: 16
              }}
            >
              How It <Text style={{ fontSize: 24, fontWeight: "bold", color: "blue" }}>Works
            </Text>
            </Text>
          </View>



          <View>
            <Image
              source={require("../assets/graphs.png")}
              style={{
                height: 73,
                width: 356,
                marginTop: 16,
                marginLeft: 5
              }}
            />
          </View>
          <View>
            <Text
              style={{
                fontSize: 24,
                fontWeight: "bold",
                marginTop: 32,
                textAlign: 'left',
                marginLeft: 16
              }}
            >
              Generate
              {" "}
              <Text style={{ fontSize: 24, fontWeight: "bold", color: "blue" }}>
             Unlimited invoices </Text>
             {"        "}
             <Text style={{
                fontSize: 24,
                fontWeight: "bold",
                marginTop: 32,
                textAlign: 'left',
                marginLeft: 16
              }}>& PDF download </Text> 
            </Text>
          </View>
          <Image
            source={require("../assets/pd.png")}
            style={{
              height: 138,
              width: 108,
              marginLeft: 16,
              marginTop: 24
            }}
          />
          <Text style={[styles.itemText2, { marginHorizontal: 10 }]}>
            Using our online invoice maker, you can generate an unlimited number
            of invoices and download them as PDF without having to pay extra.
            Free Invoice Builder will help you to make invoices in the correct
            format with all essential elements. Plus, you can easily help you
            save, track and manage all your invoices & contacts, so you will
            never lose or misplace an invoice and clients business details.
          </Text>
          <View>
            <Text
              style={{
                fontSize: 24,
                fontWeight: "bold",
                marginTop: 32,
                textAlign: 'left',
                marginLeft: 16
              }}
            >
              Create
              {" "}
              <Text style={{ fontSize: 24, fontWeight: "bold", color: "blue" }}>
             Professional </Text>
             {"              "}
             <Text style={{
                fontSize: 24,
                fontWeight: "bold",
                marginTop: 32,
                textAlign: 'left',
                marginLeft: 16
              }}>Invoice for customers </Text> 
            </Text>
          </View>
          <Image
            source={require("../assets/table.png")}
            style={{
              height: 270,
              width: 270,
              marginLeft: 11,
              marginTop: 20,
              marginBottom: 20
            }}
          />
          {/* <View style={{ alignSelf: "center", marginHorizontal: 12 }}>
            <Text
              style={{
                fontSize: 30,
                fontWeight: "700",
                top: 4,
                textAlign: "center",
                marginTop: 10,
              }}
            >
              Create Professional Invoice
              <Text style={{ fontSize: 30, fontWeight: "700", color: "blue" }}>
                {" "}
                For Customers{" "}
              </Text>
            </Text>
          </View> */}
          <Text style={[styles.itemText2, { marginHorizontal: 10 }]}>
            In this invoice tool you can Create professional invoice for your
            customers, by using an easy invoice tool you can create a healthy
            business relationship and ensure timely payments. Our easy invoice
            generator tool has unique and complete professional features like
            user-friendly interface, customizable templates, download pdf
            invoice options and easy payment options. By utilising our easy
            invoice platform, you can generate accurate and detailed invoices in
            a minute, by creating a professional invoice you focus on growing
            your business and maintaining a professional image.
            {"\n"}
            {"\n"}
            In this invoice tool there is an option that you can add your
            company logo, select colors that represent your brand, and customize
            the layout and font styles to create a cohesive and visually
            appealing invoice.
          </Text>

          <View>
            <Text
              style={{
                fontSize: 24,
                fontWeight: "bold",
                marginTop: 32,
                textAlign: 'left',
                marginLeft: 16
              }}
            >
              Access
              {" "}
              <Text style={{ fontSize: 24, fontWeight: "bold", color: "blue" }}>
             Your Invoices</Text>
             {"              "}
             <Text style={{
                fontSize: 24,
                fontWeight: "bold",
                marginTop: 32,
                textAlign: 'left',
                marginLeft: 16
              }}>Anywhere,Anytime </Text> 
            </Text>
          </View>
          <Text style={[styles.itemText2, { marginLeft: 10 }]}>
            Access Your Invoices Anywhere, Anytime! With our online invoice
            software, you can easily create and customize invoices, GST bills
            and other documents for free. You can also download your invoices
            online in different formats to ensure that they are accessible
            anytime, anywhere. Our billing software is designed to make it easy
            for you to manage all your invoicing needs with ease. With our
            software, you can quickly generate accurate invoices and save time
            while ensuring accuracy. You can track all your records from any
            other place.
            {"\n"}
            {"\n"}
            With our online invoice system, you can easily download and
            customize your billing software, free of charge.
          </Text>
          <View>
            <Text
              style={{
                fontSize: 24,
                fontWeight: "bold",
                marginTop: 32,
                textAlign: 'left',
                marginLeft: 16
              }}
            >
              For Clients Create
              {"                 "}
            
              <Text style={{ fontSize: 24, fontWeight: "bold", color: "blue" }}>
              Custom Invoice
              </Text>
              
            </Text>
          </View>
          <Text
            style={[
              styles.itemText2,
              { marginHorizontal: 10 },
            ]}
          >
            Providing clients with the facility to create custom invoices is a
            powerful way to enhance their invoicing experience and strengthen
            your business relationships. By allowing clients to tailor their
            invoices to their specific needs, you offer a level of flexibility,
            personalization, and control that promotes client satisfaction and
            loyalty. Embrace this opportunity to empower your clients and
            provide them with a seamless and intuitive invoicing process. With
            the facility to create custom invoices, you not only streamline
            their workflow but also demonstrate your commitment to meeting their
            unique business requirements :-
          </Text>
          <Text
            style={{
              fontSize: 18,
              fontWeight: "bold",
              marginLeft: 16,
              marginTop: 20,
            }}
          >
            Things You Get Customize Features In Online Billing Software Tool
          </Text>

          {News.map((item) => {
            return (
              <View
                key={item.id}
                style={{  flexDirection: "row" }}
              >
                <View>
                  <Image
                    style={styles.itemImage1}
                    source={require("../assets/blue.png")}
                  />
                </View>
                <View>
                  <Text style={{ fontSize: 16, fontWeight: "bold", marginLeft: 12, marginTop: 10 }}>
                    {item.name}
                  </Text>
                </View>
              </View>
            );
          })}
          <Image
            source={require("../assets/voice.png")}
            style={{
              height: 232,
              width: 315,
              marginTop: 24,
              marginLeft: 16
            }}
          />
          <View>
            <Text
              style={{
                fontSize: 24,
                fontWeight: "bold",
                marginTop: 32,
                textAlign: 'left',
                marginLeft: 16
              }}
            >
              Easy & Quick GST Invoice 
              {"                 "}
            
              <Text style={{ fontSize: 24, fontWeight: "bold", color: "blue" }}>
              Generator
              </Text>
              
            </Text>
          </View>
          <Text style={[styles.itemText2, { marginLeft: 14 }]}>
            Easy invoice is a completely user friendly GST invoice generator
            online software. Here, you can generate high-quality invoices
            quickly and easily. This free online receipt maker helps you to
            create professional GST invoices in just a few clicks, saving you
            time and money. With this tool, you can generate accurate invoices
            for your customers without any issue. We have provided many
            templates of different business, so that you can easily modify or
            customize the Invoice template as per your requirement.
          </Text>
          {/* <View style={{ alignSelf: "center", marginHorizontal: 12 }}>
            <Text
              style={{
                fontSize: 30,
                fontWeight: "700",
                top: 4,
                textAlign: "center",
                marginTop: 10,
              }}
            >
              Features of Easy
              <Text style={{ fontSize: 30, fontWeight: "700", color: "blue" }}>
                {" "}
                Invoice Generator{" "}
              </Text>
            </Text>
          </View>

          <View style={{ marginTop: 15 }}>
            {Voice.map((item) => {
              return (
                <View key={item.id} style={{ backgroundColor: "white" }}>
                  <View>
                    <Image
                      style={styles.itemImage3}
                      source={require("../assets/14.png")}
                    />
                  </View>
                  <View style={{ alignSelf: "center" }}>
                    <Text
                      style={{
                        fontSize: 16,
                        fontWeight: "bold",
                        textAlign: "center",
                        top: 5,
                      }}
                    >
                      {item.name}
                    </Text>
                    <Text style={{ fontSize: 14, textAlign: "center", top: 4 }}>
                      {item.value}
                    </Text>
                  </View>
                </View>
              );
            })}
          </View>

          <View style={{ alignSelf: "center", marginHorizontal: 12 }}>
            <Text
              style={{
                fontSize: 30,
                fontWeight: "700",
                top: 4,
                textAlign: "center",
                marginTop: 10,
              }}
            >
              Frequently Asked
              <Text style={{ fontSize: 30, fontWeight: "700", color: "blue" }}>
                {" "}
                Questions{" "}
              </Text>
            </Text>
          </View>

          {
              task.map((item)=>{
                return(
                  <View key={item.id} style={{ backgroundColor: 'white', flexDirection: 'row',marginTop: 2 }}>
                  <View style={{ justifyContent: 'center' ,top: 6, left:8  }}>
                  <Text style={{ fontSize: 16,fontWeight: 'bold' }}>{item.name}</Text>
                  </View>
                  <View style={{marginRight:10}}>
                    <TouchableOpacity>
                  <Image
                    style={styles.itemImage4}
                    source={require('../assets/down.png')}
                  /></TouchableOpacity></View>
                </View> */}

                {/* ) */}
              {/* }) */}
            {/* } */}

        </ScrollView>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  itemImage3: {
    width: 50,
    height: 50,
    marginBottom: 8,
    alignSelf: "center",
    top: 12,
  },
  image: {
    width: 40,
    height: 40,
    marginLeft: 12,
    borderRadius: 20,
  },
  image1: {
    width: 36,
    height: 36,
    marginTop: "auto",
    marginBottom: "auto",
    marginRight: 20,
  },
  text: {
    marginTop: 13,
    color: "white",
    marginLeft: 16,
    fontWeight: "bold",
  },
  text1: {
    marginTop: 13,
    marginLeft: 12,
    fontWeight: "800",
    fontSize: 22,
  },
  text2: {
    marginTop: 13,
    color: "blue",
    marginLeft: 12,
    fontWeight: "800",
    fontSize: 22,
  },
  button: {
    alignSelf: "center",
    width: "50%",
    backgroundColor: "#0E3AAA",
    padding: 10,
    marginHorizontal: 12,
    borderRadius: 8,
    shadowColor: "#000",
    shadowOffset: { width: 3, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    borderColor: "red",
    marginTop: 8,
  },
  buttontext: {
    textAlign: "center",
    color: "white",
    fontWeight: "500",
    fontSize: 15,
  },
  itemContainer: {
    marginTop: 10
  },
  itemText: {
    fontSize: 16,
    fontWeight: "bold",
    marginLeft: 16,
    top: 12,
  },
  itemText2: {
    fontSize: 14,
    marginLeft: 16,
    marginTop: 16,
    color: '#888888'
  },
  itemImage: {
    marginLeft: 16,
    marginTop: 24,
    width: 24,
    height: 24,
  },
  itemImage1: {
    width: 20,
    height: 20,
    marginBottom: 12,
    alignSelf: "center",
    top: 12,
    marginLeft: 16
  },
  itemImage4: {
    width: 50,
    height: 50,
    marginBottom: 11,
    alignSelf: "center",
    top: 12,
    marginHorizontal: 8
  },
});

export default Home;
